apiVersion: v1
kind: Template
metadata:
  name: build-analyzer-buildconfig
  annotations:
    description: >
      This is Thoth Build Analyzer BuildConfig, this template is meant to be used by Bots, but could also be
      used by humans...
    openshift.io/display-name: "Thoth: Build Analyzer BuildConfig"
    version: 0.4.2
    tags: thoth,ai-stacks,build-analyzer
    template.openshift.io/documentation-url: https://github.com/Thoth-Station
    template.openshift.io/long-description: >
      This is Thoth Build Analyzer BuildConfig, this template is meant to be
      used by Bots, but could also be used by humans...
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    thoth-station.ninja/template-version: 0.4.2
  labels:
    template: build-analyzer-buildconfig
    app: thoth
    component: build-analyzer

parameters:
  - description: Git repository for Thoth's Build Analyzer
    displayName: Thoth Build Analyzer git repository
    required: true
    name: GITHUB_URL
    value: "https://github.com/thoth-station/build-analyzers"

  - description: Git repository for Thoth's Build Analyzer
    displayName: Thoth Build Analyzer git reference
    required: true
    name: GITHUB_REF
    value: "master"

  - description: Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: "latest"

  - description: Thamos Advise setup tag value
    displayName: THOTH_ADVISE
    required: true
    name: THOTH_ADVISE
    value: "1"

objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: thoth
        component: build-analyzer
      annotations:
        thoth-station.ninja/template-version: 0.4.2
      name: build-analyzer
    spec:
      resources:
        limits:
          cpu: 1
          memory: 768Mi
        requests:
          cpu: 1
          memory: 768Mi
      output:
        to:
          kind: ImageStreamTag
          name: "build-analyzer:${IMAGE_STREAM_TAG}"
      runPolicy: Serial
      source:
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
        type: Git
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: s2i-thoth-ubi8-py36:latest
          env:
            - name: ENABLE_PIPENV
              value: "1"
            - name: UPGRADE_PIP_TO_LATEST
              value: ""
            - name: APP_FILE
              value: "thoth-build-analyzer"
            - name: "THOTH_DRY_RUN"
              value: "1"
            - name: "THOTH_ADVISE"
              value: ${THOTH_ADVISE}
            - name: "THAMOS_VERBOSE"
              value: "1"
            - name: "THAMOS_DEBUG"
              value: "0"
            - name: "THAMOS_CONFIG_TEMPLATE"
              value: ".thoth.yaml"
            - name: "THAMOS_CONFIG_EXPAND_ENV"
              value: "1"
      triggers:
        - imageChange: {}
          type: ImageChange
        - type: "Generic"
          generic:
            secretReference:
              name: generic-webhook-secret
